spring:
  datasource:
    url: jdbc:postgresql://localhost:8888/invoicing
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true

invoicing-system:
  database: sql