server:
  port: 7778

logging:
  level:
    org:
      springframework:
        boot: INFO
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG

spring:
  profiles:
    active: sql
  flyway:
    enabled: false

