server:
  port: 7778

logging:
  level:
    org:
      springframework:
        boot: INFO
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG

spring:
  profiles:
    active: file
  flyway:
    enabled: false
  security:
    user:
      name: katkatee
      password: lala123

invoicing-system:
  allowedOrigins: http://localhost:4200
  csrf:
    disable: true

