spring:
  datasource:
    url: jdbc:postgresql://localhost:8888/invoicing-test
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true

invoicing-system:
  database: sql